FROM ros:humble

RUN apt update && \
    apt install -y software-properties-common && \
    apt install -y ros-humble-demo-nodes-cpp && \
    apt install -y python3-colcon-common-extensions && \
    apt upgrade -y

RUN apt install -y \
    nano \
    byobu

RUN apt install -y qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools && \
    apt install -y dbus-x11 x11-xserver-utils

ENV QT_QPA_PLATFORM=xcb

RUN apt-get install -y python3 python3-pip && \
    pip install pyserial

RUN mkdir -p /wolvi/src

RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc && \
    echo "source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash" >> /root/.bashrc && \
    echo "source /wolvi/install/setup.bash" >> /root/.bashrc

CMD ["bash", "-c", "\
    source /opt/ros/humble/setup.bash && \
    source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash && \
    exec bash"]
